#!/usr/bin/bash

battery_info=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0)
battery_percentage=$(echo "$battery_info" | grep "percentage" | awk '{print $2}')
battery_percentage=$(echo $battery_percentage | tr -d "%")
battery_state=$(echo "$battery_info" | grep "state" | awk '{print $2}')

echo "{\"value\": \"$battery_percentage\", \"state\": \"$battery_state\"}"
