#!/bin/sh

. "$HOME"/.config/river/autostart.sh
. "$HOME"/.config/river/input.sh
. "$HOME"/.config/river/keymaps.sh
. "$HOME"/.config/river/ui.sh

# Initial Tags
riverctl rule-add -app-id code-url-handler tags 1          # (tag 1)
riverctl rule-add -app-id firefox tags 2                   # (tag 2)
riverctl rule-add -app-id Spotify -title Spotify tags 4    # (tag 3)
riverctl rule-add -app-id vesktop tags 8                   # (tag 4)
riverctl rule-add -app-id gthumb tags 16                   # (tag 5)
riverctl rule-add -app-id Spotify -title Syncthing tags 16 # (tag 5)

# Miscellaenous
riverctl xcursor-theme phinger-cursors-light 24
riverctl attach-mode bottom
riverctl border-width 1
riverctl focus-follows-cursor normal
riverctl set-cursor-warp on-output-change

riverctl default-layout rivertile
rivertile -view-padding 2 -outer-padding 2 -main-ratio 0.50 &
