#!/bin/sh

. "$HOME"/.config/river/autostart.sh
. "$HOME"/.config/river/input.sh
. "$HOME"/.config/river/keymaps.sh
. "$HOME"/.config/river/ui.sh

# Initial Tags
riverctl rule-add -app-id code-url-handler tags 1          # (tag 1)
riverctl rule-add -app-id firefox tags 2                   # (tag 2)
riverctl rule-add -app-id Spotify -title Spotify tags 4    # (tag 3)
riverctl rule-add -app-id vesktop tags 8                   # (tag 4)
riverctl rule-add -app-id gthumb tags 16                   # (tag 5)
riverctl rule-add -app-id Spotify -title Syncthing tags 16 # (tag 5)

# Miscellaenous
riverctl xcursor-theme phinger-cursors-light 24
riverctl attach-mode bottom
riverctl border-width 1
riverctl focus-follows-cursor normal
riverctl set-cursor-warp on-output-change

riverctl default-layout wideriver
wideriver \
	--layout                       left        \
	--layout-alt                   monocle     \
	--stack                        dwindle     \
	--count-master                 1           \
	--no-smart-gaps                            \
	--inner-gaps                   5           \
	--outer-gaps                   5           \
	--border-width                 1           \
	--border-width-monocle         0           \
	--border-width-smart-gaps      0           \
	--border-color-focused         "0xbf7979"  \
	--border-color-focused-monocle "0x586e75"  \
	--border-color-unfocused       "0xc9b9a7"  \
	--log-threshold                info        \
	> "/tmp/wideriver.${XDG_VTNR}.${USER}.log" 2>&1 &
