abbr --add g "git"
abbr --add gs "git status"
abbr --add gss "git status -s"

abbr --add rd "ripdrag -a -r"
abbr --add v "nvim"
abbr --add p "pacman"
abbr --add py "python"
abbr --add l "lfcd"
abbr --add m "make"
abbr --add dk "docker"
abbr --add uvr "uv run"
abbr --add uvm "uv run manage.py"
abbr --add nmt "nmtui"
abbr --add nmc "nmcli"

abbr --add ls "ls -hN --color=auto --group-directories-first"
abbr --add exa "exa --group-directories-first"
abbr --add c "clear"
abbr --add clera "clear"
abbr --add q "exit"
abbr --add quit "exit"
abbr --add qquit "exit"
abbr --add md "mkdir -p"

abbr --add pubip "curl ipinfo.io; echo"
abbr --add copy "wl-copy"
abbr --add pkg "pacman -Q | wc -l"
abbr --add bt "upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep percentage | awk '{print $2}'"
