import = [
	"~/.config/alacritty/swamp-light.toml"
]

[font]
normal = { family = "IBM Plex Mono", style = "Regular" }
size = 10

[window]
padding = { x = 5, y = 5 }

[cursor]
style = { shape = "Beam", blinking = "On" }
unfocused_hollow = true
