[font]
normal = { family = "Fairfax Hax", style = "Regular" }
size = 18

[window]
padding = { x = 5, y = 5 }

[cursor]
style = { shape = "Beam", blinking = "On" }
unfocused_hollow = true

[general]
import = [
	"~/.config/alacritty/swamp-light.toml"
]
