theme = "swamp light"
client_id = "b60844fa1c1b48e3bc1b77f530ba02a1"
client_port = 8080
playback_format = """
{track} • {artists}
{album}
{metadata}
"""
tracks_playback_limit = 50
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
page_size_in_rows = 20
play_icon = "▶"
pause_icon = "⏸"
liked_icon = "♥"
border_type = "Hidden"
progress_bar_type = "Rectangle"
playback_window_position = "Top"
playback_window_width = 5
enable_media_control = true
enable_streaming = "Always"
enable_notify = true
enable_cover_image_cache = false
default_device = "sharktooth"
notify_streaming_only = false

[copy_command]
command = "xclip"
args = [
    "-sel",
    "c",
]

[notify_format]
summary = "{track}"
body = "{artists}"

[device]
name = "sharktooth"
device_type = "computer"
volume = 75
bitrate = 320
audio_cache = false
normalization = false
